In [1]:
import pandas as pd

df = pd.read_csv('European_Bank.csv')
df.head()

,Year,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,2025,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2025,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,2025,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,2025,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,2025,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [2]:
df['BalanceSalaryRatio'] = df['Balance'] / df['EstimatedSalary']
df[['Balance', 'EstimatedSalary', 'BalanceSalaryRatio']].head()

     Balance  EstimatedSalary  BalanceSalaryRatio
0       0.00        101348.88            0.000000
1   83807.86        112542.58            0.744677
2  159660.80        113931.57            1.401375
3       0.00         93826.63            0.000000
4  125510.82         79084.10            1.587055

In [3]:
df['HighProductDensity'] = (df['NumOfProducts'] >= 3).astype(int)
df[['NumOfProducts', 'HighProductDensity']].head(10)

   NumOfProducts  HighProductDensity
0              1                   0
1              1                   0
2              3                   1
3              2                   0
4              1                   0
5              2                   0
6              2                   0
7              4                   1
8              2                   0
9              1                   0

In [4]:
df['EngagementProductInteraction'] = df['IsActiveMember'] * df['NumOfProducts']
df[['IsActiveMember', 'NumOfProducts', 'EngagementProductInteraction']].head(10)

   IsActiveMember  NumOfProducts  EngagementProductInteraction
0               1              1                             1
1               1              1                             1
2               0              3                             0
3               0              2                             0
4               1              1                             1
5               0              2                             0
6               1              2                             2
7               0              4                             0
8               1              2                             2
9               1              1                             1

In [5]:
df['AgeTenureInteraction'] = df['Age'] * df['Tenure']
df[['Age', 'Tenure', 'AgeTenureInteraction']].head(10)

   Age  Tenure  AgeTenureInteraction
0   42       2                    84
1   41       1                    41
2   42       8                   336
3   39       1                    39
4   43       2                    86
5   44       8                   352
6   50       7                   350
7   29       4                   116
8   44       4                   176
9   27       2                    54

In [6]:
df.groupby('Exited')[['BalanceSalaryRatio', 'HighProductDensity', 'EngagementProductInteraction', 'AgeTenureInteraction']].mean()

,BalanceSalaryRatio,HighProductDensity,EngagementProductInteraction,AgeTenureInteraction
Exited,,,,
0,2.478339,0.005777,0.851689,188.215622
1,9.352977,0.137457,0.553756,220.559156

In [7]:
df.to_csv('European_Bank_features.csv', index=False)