In [1]:
import pandas as pd

df = pd.read_csv('European_Bank_features.csv')
df.head()

,Year,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,BalanceSalaryRatio,HighProductDensity,EngagementProductInteraction,AgeTenureInteraction
0,2025,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1,0.000000,0,1,84
1,2025,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0,0.744677,0,1,41
2,2025,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1,1.401375,1,0,336
3,2025,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0,0.000000,0,0,39
4,2025,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0,1.587055,0,1,86

In [2]:
df = df.drop(columns=['CustomerId', 'Surname', 'Year'])
df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,BalanceSalaryRatio,HighProductDensity,EngagementProductInteraction,AgeTenureInteraction
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1,0.000000,0,1,84
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0,0.744677,0,1,41
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1,1.401375,1,0,336
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0,0.000000,0,0,39
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0,1.587055,0,1,86

In [3]:
df = pd.get_dummies(df, columns=['Geography', 'Gender'], drop_first=True)
df.head()

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,BalanceSalaryRatio,HighProductDensity,EngagementProductInteraction,AgeTenureInteraction,Geography_Germany,Geography_Spain,Gender_Male
0,619,42,2,0.00,1,1,1,101348.88,1,0.000000,0,1,84,False,False,False
1,608,41,1,83807.86,1,0,1,112542.58,0,0.744677,0,1,41,False,True,False
2,502,42,8,159660.80,3,1,0,113931.57,1,1.401375,1,0,336,False,False,False
3,699,39,1,0.00,2,0,0,93826.63,0,0.000000,0,0,39,False,False,False
4,850,43,2,125510.82,1,1,1,79084.10,0,1.587055,0,1,86,False,True,False

In [4]:
df = pd.get_dummies(df, columns=['Geography', 'Gender'], drop_first=True)
df.head()

KeyError: "None of [Index(['Geography', 'Gender'], dtype='object')] are in the [columns]"

In [5]:
df.columns

Index(['CreditScore', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited', 'BalanceSalaryRatio',
       'HighProductDensity', 'EngagementProductInteraction',
       'AgeTenureInteraction', 'Geography_Germany', 'Geography_Spain',
       'Gender_Male'],
      dtype='object')

In [6]:
X = df.drop(columns=['Exited'])
y = df['Exited']

X.head()

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,BalanceSalaryRatio,HighProductDensity,EngagementProductInteraction,AgeTenureInteraction,Geography_Germany,Geography_Spain,Gender_Male
0,619,42,2,0.00,1,1,1,101348.88,0.000000,0,1,84,False,False,False
1,608,41,1,83807.86,1,0,1,112542.58,0.744677,0,1,41,False,True,False
2,502,42,8,159660.80,3,1,0,113931.57,1.401375,1,0,336,False,False,False
3,699,39,1,0.00,2,0,0,93826.63,0.000000,0,0,39,False,False,False
4,850,43,2,125510.82,1,1,1,79084.10,1.587055,0,1,86,False,True,False

In [7]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=42
)

print(X_train.shape)
print(X_test.shape)

(8000, 15)
(2000, 15)

In [8]:
print(y_train.value_counts(normalize=True))
print(y_test.value_counts(normalize=True))

Exited
0    0.79625
1    0.20375
Name: proportion, dtype: float64
Exited
0    0.7965
1    0.2035
Name: proportion, dtype: float64

In [9]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

numeric_cols = ['CreditScore', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 
                 'EstimatedSalary', 'BalanceSalaryRatio', 'EngagementProductInteraction', 
                 'AgeTenureInteraction']

X_train[numeric_cols] = scaler.fit_transform(X_train[numeric_cols])
X_test[numeric_cols] = scaler.transform(X_test[numeric_cols])

X_train.head()

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,BalanceSalaryRatio,HighProductDensity,EngagementProductInteraction,AgeTenureInteraction,Geography_Germany,Geography_Spain,Gender_Male
2151,1.058568,1.715086,0.684723,-1.226059,-0.910256,1,0,1.042084,-0.034927,0,-0.908608,1.580589,False,False,True
8392,0.913626,-0.659935,-0.696202,0.413288,-0.910256,1,0,-0.623556,-0.021722,0,-0.908608,-0.770341,True,False,True
5006,1.079274,-0.184931,-1.731895,0.601687,0.808830,1,1,0.308128,-0.026903,0,1.390574,-1.515190,True,False,False
4117,-0.929207,-0.184931,-0.005739,-1.226059,0.808830,1,0,-0.290199,-0.034927,0,-0.908608,-0.079804,False,False,True
7182,0.427035,0.955079,0.339492,0.548318,0.808830,0,1,0.135042,-0.026418,0,1.390574,0.765910,True,False,True

In [10]:
X_train.to_csv('X_train.csv', index=False)
X_test.to_csv('X_test.csv', index=False)
y_train.to_csv('y_train.csv', index=False)
y_test.to_csv('y_test.csv', index=False)